import { taskService, shoppingService } from '../services/taskable'

export const taskConfig = {
  table: 'tasks',
  entity: 'task',
  title: 'Tareas',
  listTitle: 'Tareas pendientes',
  historyTitle: 'Historial de tareas',
  fieldName: 'title',
  doneField: 'is_done',
  doneAtField: 'done_at',
  iconName: 'task',
  createTitle: 'Nueva tarea',
  editTitle: 'Editar tarea',
  inputPlaceholder: 'Título de la tarea',
  emptyMessage: 'Aún no hay tareas pendientes.',
  emptyListMessage: 'No hay tareas pendientes.',
  emptyHistoryMessage: 'No hay tareas completadas.',
  confirmTitle: '¿Marcar como hecha?',
  confirmLabel: 'Hecho',
  unconfirmTitle: '¿Desmarcar tarea?',
  unconfirmLabel: 'Desmarcar',
  deleteConfirm: '¿Borrar esta tarea?',
  service: taskService,
}

export const shoppingConfig = {
  table: 'shopping_items',
  entity: 'shopping',
  title: 'Compra',
  listTitle: 'Lista de la compra',
  historyTitle: 'Historial de compra',
  fieldName: 'name',
  doneField: 'is_bought',
  doneAtField: 'bought_at',
  iconName: 'shoppingCart',
  createTitle: 'Nuevo artículo',
  editTitle: 'Editar artículo',
  inputPlaceholder: 'Nombre del artículo',
  emptyMessage: 'Aún no hay nada pendiente para comprar.',
  emptyListMessage: 'No hay artículos pendientes.',
  emptyHistoryMessage: 'No hay artículos comprados.',
  confirmTitle: '¿Marcar como comprado?',
  confirmLabel: 'Comprado',
  unconfirmTitle: '¿Desmarcar artículo?',
  unconfirmLabel: 'Desmarcar',
  deleteConfirm: '¿Borrar este artículo?',
  service: shoppingService,
}
